### ISSUE TITLE
Update Jenkins to test image based on PR changes

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#159]
We should update the [Jenkins config](https://ci.openshift.redhat.com/jenkins/job/mongodb/) to run extended tests with the image that we build in PRs, not the image from DockerHub, otherwise it takes a few iterations to realize that tests are not passing -- after a PR was merged. Example: https://github.com/openshift/mongodb/pull/154.

@bparees @php-coder @mfojtik FYI

**Comment by bparees** [comment]
the only way to do this is for the template used by the extended tests to not use an imagechangetrigger but instead to hardcode the image field in the DC.

which is not what we'd want for when the extended test is run in origin, since the purpose of that run is to, among other things, validate the template and the imagestream is part of that template.

so if we want reuse of the extended test between origin and here, we're kinda stuck at the moment.

**Comment by rhcarvalho** [comment]
@bparees the [replication example template](https://github.com/openshift/mongodb/blob/master/2.4/examples/replica/mongodb-clustered.json) doesn't include an image stream, it just [points to the image openshift/mongo-24-centos7](https://github.com/openshift/mongodb/blob/master/2.4/examples/replica/mongodb-clustered.json#L127).

The [config](https://ci.openshift.redhat.com/jenkins/job/mongodb/configure#yui-gen11) today executes:

```
# ...

vagrant test-origin-image --image mongodb --source openshift/$JOB_NAME --ref $ghprbActualCommit

# Run the "mongo" extended tests when comment contains [openshift]
if [[ "${ghprbCommentBody}" == *"[openshift]"* ]]; then
  vagrant ssh -c "docker images"
  vagrant test-origin --extended "core(mongo)" -d --skip-check --skip-image-cleanup
fi

# ...
```

IIRC `vagrant test-origin-image` builds an image called `openshift/mongo-24-centos7-candidate`. A quick fix would be to tag this image as `openshift/mongo-24-centos7`, after `vagrant test-origin-image` and before `vagrant test-origin`.

WDYT?

**Comment by bparees** [comment]
@rhcarvalho the make test job already includes the option to TAG_ON_SUCCESS=true, so if we just make sure that is set when we do the make test call, it sounds like we're fine?

**Comment by rhcarvalho** [comment]
I didn't know about that tag, that should do it I suppose.
When the PR tester will be working again I could create a PR to ensure the tests break when they should.

**Comment by omron93** [comment]
Currently it is possible to run test of replication in OpenShift by mentioning [test-openshift] (#222) in comment. This tests image which sources are in Pull Request.

So I hope this issue is fixed. (also there is new CI, so it is probably outdated)

Note: Adding new or extending current OpenShift testing scenarios can be done by modifying `test/run-openshift` script in for example in `3.2/` folder.
