### ISSUE TITLE
Publish Mongodb 4 image

### ISSUE THREAD

**Issue by ehvs** [sclorg/mongodb-container#297]
Hi team,

Do we have an estimated date to be published Mongodb 4 image?

**Comment by omron93** [comment]
Hi,
this github repos contains files for three types of images: RHEL7, Centos7 and Fedora.

To request addition of a new Red Hat Software Collection please use http://bugzilla.redhat.com/. A new centos based image is added basically after rebuild of released RHSCL packages.

So now only Fedora based image for Mongodb 4.0 could be added. If you are looking for Fedora based variant, then I could add it.
If not, I would wait for RHEL variant. It's because of the fact, that automated building of fedora images is not working well right now and it has to be done manually. So a lot of fedora images is outdated. I'm currently working on it, so I would wait with adding image with _only_ fedora variant till having working rebuild process.

**Comment by lehmeyer** [comment]
I have opened a ticket at redhat for this https://bugzilla.redhat.com/show_bug.cgi?id=1705905

**Comment by hhorak** [comment]
I'm sorry, but since the MongoDB upstream changed a license to SSPL for the server, we cannot add any further versions to the Fedora and RHEL. More information also available in https://fedoraproject.org/wiki/Changes/MongoDB_Removal.

**Comment by BorntraegerMarc** [comment]
Thank you @hhorak for posting this link.

Please correct me if I'm wrong: But shouldn't this repository be marked as `deprecated` or `non supported`? If I understand the MongDB removal from Fedora correctly it means that no version will ever receive any update ever again. Also not minor bug-fix updates.

I think this is quite an important point. users should aware of this when browsing this repo, wouldn't you agree?

For me it means that this repo `mongodb-container` is not suitable for long term use as it's not supported anymore. So I will need to search for alternatives.

Please correct me, in case I understood something wrong. I'm pretty new to openshift / k8 😄

**Comment by pkubatrh** [comment]
Hi @BorntraegerMarc 

there will be no new MongoDB versions (= no MongoDB 4.0 and onwards), but existing RHSCLs will still be supported according to their [lifecycle](https://access.redhat.com/support/policy/updates/rhscl). As long as the RHSCL RPMs are supported, the images will not get deprecated either.

Note that this is applies to CentOS and RHEL versions of images. Fedora versions will be quickly deprecated when there is no Fedora version that has MongoDB available.
