### ISSUE TITLE
Infinite loop when deploying with replicas set to 0

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#72]
Trying to (re)deploy with replicas set to 0 will start an infinite loop [here](https://github.com/openshift/mongodb/blob/57042b34f5577f31e2117e9fafcc1112a492efa5/2.4/contrib/initiate_replica.sh#L5-L12) which will cause the deployment to never complete.

**Comment by bparees** [comment]
@rhcarvalho is this still an issue?

**Comment by rhcarvalho** [comment]
The code I pointed in the issue moved to a new place: [initiate_replica.sh#L5-L12](https://github.com/openshift/mongodb/blob/5cbbefc17524d971b929446692e32fd437b9ac21/2.4/root/usr/share/container-scripts/mongodb/initiate_replica.sh#L5-L12).

Yes, still an issue.

**Comment by omron93** [comment]
Using of `ReplSet` was removed (now using `PetSet` kubernetes replication - no deploy hook is used) and I hope this issue is no longer valid for `PetSet` (is working for me).

Feel free to reopen.

**Comment by rhcarvalho** [comment]
This is unrelated to ReplSet/PetSet.

The bug should manifest itself on a corner case, when replicas=0.

Today the code that (probably, haven't tested, haven't used for a long time) loops forever is:

https://github.com/sclorg/mongodb-container/blob/12a0b41100d9a555c4b5674550467aaea01c527a/2.4/root/usr/share/container-scripts/mongodb/init-replset.sh#L10-L27

**Comment by omron93** [comment]
> This is unrelated to ReplSet/PetSet.

@rhcarvalho If I understand it right, it is.

With `ReplSet` there was a container (deploy hook), not listed in Service which tested that some containers are listed there. So after scale to 0, this deploy hook container was waiting for containers forever.

Now with `PetSet` there is no such hook container. So after scale to 0, there is no container where "forever loop" could run.

But forever loops in normal container code (NOT in code for signal handling or code in deploy hook) are helpful, because if something gets wrong (~ container freezes in loop), it is not reported as ready and it is restarted after some time.

**Comment by rhcarvalho** [comment]
@omron93 okay, I don't remember/know how is the current state of the code. Your explanation makes perfect sense, thank you. And thanks for closing and updating this and many other old issues/PRs! :+1:
